import { useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen } from 'lucide-react';
import { motion } from 'framer-motion';
import Button from '../shared/Button';

// Mock data for showcase
const samples = [
    { id: '1', title: 'The Fall of Rome', pages: 12, color: 'bg-red-500' },
    { id: '2', title: 'How Photosynthesis Works', pages: 10, color: 'bg-green-500' },
    { id: '3', title: 'Einstein\'s Relativity', pages: 14, color: 'bg-blue-500' },
    { id: '4', title: 'The World of Shakespeare', pages: 12, color: 'bg-purple-500' },
];

export default function SampleShowcase() {
    const navigate = useNavigate();
    const scrollRef = useRef(null);

    // Auto-scroll effect
    useEffect(() => {
        const el = scrollRef.current;
        if (!el) return;

        const interval = setInterval(() => {
            if (el.scrollLeft + el.clientWidth >= el.scrollWidth) {
                el.scrollTo({ left: 0, behavior: 'smooth' });
            } else {
                el.scrollBy({ left: 300, behavior: 'smooth' });
            }
        }, 5000);

        return () => clearInterval(interval);
    }, []);

    return (
        <section className="py-20 bg-slate-50 overflow-hidden">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex flex-col md:flex-row items-end justify-between mb-12 gap-4">
                    <motion.div
                        initial={{ opacity: 0, x: -30 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.6 }}
                    >
                        <h2 className="text-3xl md:text-5xl font-heading text-gray-900 mb-2">
                            Featured Creations
                        </h2>
                        <p className="text-gray-600">Explore comics generated by our community</p>
                    </motion.div>
                    <Button
                        variant="ghost"
                        onClick={() => navigate('/gallery')}
                        className="text-indigo-600 hover:text-indigo-700"
                    >
                        View All <ArrowRight className="ml-2 w-4 h-4" />
                    </Button>
                </div>

                <div
                    ref={scrollRef}
                    className="flex gap-6 overflow-x-auto pb-8 snap-x snap-mandatory scrollbar-hide"
                    style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
                >
                    {samples.map((sample, index) => (
                        <motion.div
                            key={sample.id}
                            initial={{ opacity: 0, scale: 0.9 }}
                            whileInView={{ opacity: 1, scale: 1 }}
                            viewport={{ once: true }}
                            transition={{ duration: 0.5, delay: index * 0.1 }}
                            className="flex-none w-72 md:w-80 snap-center"
                        >
                            <div className="group relative aspect-[2/3] rounded-xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-2 cursor-pointer bg-white">
                                {/* Fallback color if no image */}
                                <div className={`absolute inset-0 ${sample.color} opacity-20 group-hover:opacity-30 transition-opacity`} />
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <BookOpen className="w-16 h-16 text-gray-400/50" />
                                </div>

                                {/* Content Overlay */}
                                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-90" />

                                <div className="absolute bottom-0 left-0 right-0 p-6 text-white">
                                    <h3 className="text-xl font-bold font-heading mb-1 line-clamp-2">{sample.title}</h3>
                                    <p className="text-sm text-gray-300 mb-4">{sample.pages} Pages</p>
                                    <Button
                                        size="sm"
                                        fullWidth
                                        variant="secondary"
                                        className="opacity-0 group-hover:opacity-100 transition-opacity transform translate-y-2 group-hover:translate-y-0"
                                        onClick={() => navigate(`/comic/${sample.id}`)}
                                    >
                                        Read Comic
                                    </Button>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>

            {/* Call to Action */}
            <div className="container mx-auto px-4 mt-16">
                <motion.div
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.8 }}
                    className="bg-indigo-600 rounded-3xl p-8 md:p-16 text-center text-white relative overflow-hidden shadow-xl"
                >
                    <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -mr-32 -mt-32" />
                    <div className="absolute bottom-0 left-0 w-64 h-64 bg-pink-500/20 rounded-full blur-3xl -ml-32 -mb-32" />

                    <div className="relative z-10 max-w-2xl mx-auto">
                        <h2 className="text-3xl md:text-5xl font-heading mb-6">Ready to Create Your Masterpiece?</h2>
                        <p className="text-indigo-100 text-lg mb-8">
                            Join thousands of students and make studying unforgettable today.
                        </p>
                        <Button
                            size="lg"
                            variant="secondary"
                            className="bg-white text-indigo-600 border-none hover:bg-gray-100 shadow-xl"
                            onClick={() => navigate('/create')}
                        >
                            Get Started Now <ArrowRight className="ml-2 w-5 h-5" />
                        </Button>
                    </div>
                </motion.div>
            </div>
        </section>
    );
}
